import {
  CheckCircle,
  FileCode,
  Rocket,
  Workflow,
  ArrowRight,
} from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function GettingStartedPage() {
  return (
    <main className="min-h-screen bg-white text-zinc-900">
      {/* HEADER */}
      <div className="mx-auto max-w-5xl px-6 pb-16 pt-32">
        <h1 className="text-4xl font-bold tracking-tight text-zinc-900 sm:text-5xl">
          Getting Started
        </h1>
        <p className="mt-4 text-lg text-zinc-600 max-w-2xl">
          Learn how to build full-stack applications with AvatarFlowX using
          visual flows and autogenerated backend & frontend logic.
        </p>

        <div className="mt-8 flex gap-4">
          <Button asChild className="rounded-full h-11 px-6 text-base">
            <Link href="/flow">
              Open Visual Builder <ArrowRight className="ml-2 h-4" />
            </Link>
          </Button>

          <Button
            asChild
            variant="outline"
            className="rounded-full h-11 px-6 text-base border-zinc-300 text-zinc-700"
          >
            <Link href="/">Back Home</Link>
          </Button>
        </div>
      </div>

      {/* SECTIONS */}
      <section className="mx-auto max-w-5xl px-6 space-y-16 pb-32">
        {/* INTRO */}
        <div>
          <h2 className="text-2xl font-semibold mb-4">What is AvatarFlowX?</h2>
          <p className="text-zinc-700 leading-relaxed">
            AvatarFlowX lets you design your full application visually. Instead
            of manually creating routes, schemas, API handlers, UI screens, and
            backend logic, you drag & connect nodes — and everything is
            generated automatically.
          </p>
        </div>

        {/* STEPS */}
        <div className="grid gap-10 md:grid-cols-3">
          {/* STEP 1 */}
          <div className="p-6 rounded-2xl border border-zinc-200 shadow-sm bg-white">
            <Workflow className="h-8 w-8 text-blue-600" />
            <h3 className="mt-4 text-xl font-semibold">1. Create Your Flow</h3>
            <p className="mt-2 text-zinc-600">
              Drag nodes to define pages, data schemas, business logic, APIs,
              authentication, and more.
            </p>
          </div>

          {/* STEP 2 */}
          <div className="p-6 rounded-2xl border border-zinc-200 shadow-sm bg-white">
            <Rocket className="h-8 w-8 text-purple-600" />
            <h3 className="mt-4 text-xl font-semibold">
              2. AI Generates the App
            </h3>
            <p className="mt-2 text-zinc-600">
              AvatarFlowX instantly transforms your visual flow into
              production-ready backend and frontend code.
            </p>
          </div>

          {/* STEP 3 */}
          <div className="p-6 rounded-2xl border border-zinc-200 shadow-sm bg-white">
            <FileCode className="h-8 w-8 text-teal-600" />
            <h3 className="mt-4 text-xl font-semibold">3. Export or Deploy</h3>
            <p className="mt-2 text-zinc-600">
              Download the generated code or ship directly — APIs, schema, UI,
              logic, and routes included.
            </p>
          </div>
        </div>

        {/* LONG CONTENT — REAL DOCS FEEL */}
        <div className="space-y-10">
          <div>
            <h2 className="text-2xl font-semibold mb-4">Installation</h2>
            <p className="text-zinc-700">
              No installation needed. Visit the builder and start creating your
              application visually.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4">
              Generated Project Structure
            </h2>
            <pre className="bg-zinc-900 text-white p-6 rounded-xl text-sm overflow-x-auto shadow-md">
              {`my-app/
 ├─ app/
 │   ├─ api/
 │   ├─ components/
 │   ├─ pages/
 │   └─ layout.tsx
 ├─ models/
 ├─ prisma/
 ├─ routes/
 └─ package.json`}
            </pre>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4">Next Steps</h2>
            <ul className="space-y-3 text-zinc-700">
              <li className="flex items-center gap-2">
                <CheckCircle className="h-5 text-green-600" /> Learn how visual
                nodes work
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle className="h-5 text-green-600" /> Build a simple
                API flow
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle className="h-5 text-green-600" /> Connect UI
                screens with backend logic
              </li>
            </ul>
          </div>

          <div className="pt-4">
            <Button asChild className="rounded-full h-11 px-6 text-base">
              <Link href="/flow">Start Building →</Link>
            </Button>
          </div>
        </div>
      </section>
    </main>
  );
}
