import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { HeroHeader } from "@/components/header";
import Features from "@/components/features-4";
import { ChevronRight } from "lucide-react";
import IntegrationsSection from "@/components/integrations-7";

export default function HeroSection() {
  return (
    <>
      <HeroHeader />

      <main className="relative overflow-hidden">
        <video
          autoPlay
          muted
          loop
          playsInline
          className="absolute inset-0 w-full h-full object-cover opacity-80 dark:opacity-70"
          src="https://ik.imagekit.io/lrigu76hy/tailark/dna-video.mp4?updatedAt=1745736251477"
        />

        <div className="absolute inset-0 bg-black/20 dark:bg-black/40" />

        <section className="relative z-20">
          <div className="mx-auto max-w-7xl px-6 pt-40 pb-48 lg:px-12">
            <div className="max-w-3xl text-left">
              <h1 className="text-5xl md:text-6xl xl:text-7xl font-bold leading-tight text-white">
                Build Full Apps Visually. <br /> No Code. No Limits.
              </h1>

              <p className="mt-6 max-w-2xl text-lg text-white/90">
                Draw your flow. AvatarFlowX instantly converts it into a working
                app — UI, backend, APIs, logic — everything autogenerated with
                AI.
              </p>

              <div className="mt-10 flex flex-col sm:flex-row gap-4">
                <Button
                  asChild
                  size="lg"
                  className="h-12 rounded-full text-base bg-white text-black hover:bg-neutral-200"
                >
                  <Link href="/flow">
                    Go to Builder <ChevronRight className="ml-2" />
                  </Link>
                </Button>

                <Button
                  asChild
                  size="lg"
                  variant="outline"
                  className="h-12 rounded-full text-base border-white text-white hover:bg-white/10"
                >
                  <Link href="/docs/getting-started">Learn How It Works</Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* ⭐ ADD FEATURES SECTION HERE ⭐ */}
      <Features />

      <IntegrationsSection />
    </>
  );
}
