/**
 * Element Templates
 * Pre-configured templates for all premium visual builder elements
 */

import { ElementTemplate } from '../visual-builder-types';

export const ELEMENT_TEMPLATES: ElementTemplate[] = [
    // ============= BASIC ELEMENTS =============
    {
        type: 'text',
        category: 'basic',
        name: 'Text',
        icon: '📝',
        description: 'Simple text element',
        defaultProperties: { text: 'Enter text here' },
        defaultStyles: { fontSize: '16px', color: '#000000' },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'heading',
        category: 'basic',
        name: 'Heading',
        icon: '🔤',
        description: 'Large heading text',
        defaultProperties: { text: 'Heading', level: '1' },
        defaultStyles: { fontSize: '32px', fontWeight: '700', color: '#000000' },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'paragraph',
        category: 'basic',
        name: 'Paragraph',
        icon: '📄',
        description: 'Text paragraph',
        defaultProperties: { text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
        defaultStyles: { fontSize: '16px', lineHeight: '1.6', color: '#333333' },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'button',
        category: 'basic',
        name: 'Button',
        icon: '🔘',
        description: 'Clickable button',
        defaultProperties: { label: 'Click Me', variant: 'primary' },
        defaultStyles: {
            padding: '12px 24px',
            backgroundColor: '#3b82f6',
            color: '#ffffff',
            border: 'none',
            borderRadius: '6px',
            cursor: 'pointer',
            fontWeight: '500',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'link',
        category: 'basic',
        name: 'Link',
        icon: '🔗',
        description: 'Hyperlink',
        defaultProperties: { text: 'Link', href: '#', target: '_self' },
        defaultStyles: { color: '#3b82f6', textDecoration: 'underline', cursor: 'pointer' },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'icon',
        category: 'basic',
        name: 'Icon',
        icon: '⭐',
        description: 'Icon element',
        defaultProperties: { icon: 'star' },
        defaultStyles: { fontSize: '24px', color: '#000000' },
        defaultSize: { width: '24px', height: '24px' },
    },
    {
        type: 'divider',
        category: 'basic',
        name: 'Divider',
        icon: '➖',
        description: 'Horizontal line',
        defaultProperties: {},
        defaultStyles: {
            borderTop: '1px solid #e5e7eb',
            width: '100%',
            margin: '20px 0',
        },
        defaultSize: { width: '100%', height: '1px' },
    },
    {
        type: 'spacer',
        category: 'basic',
        name: 'Spacer',
        icon: '↕️',
        description: 'Empty space',
        defaultProperties: {},
        defaultStyles: {},
        defaultSize: { width: '100%', height: '40px' },
    },

    // ============= LAYOUT ELEMENTS =============
    {
        type: 'container',
        category: 'layout',
        name: 'Container',
        icon: '📦',
        description: 'Content container',
        defaultProperties: {},
        defaultStyles: {
            maxWidth: '1200px',
            margin: '0 auto',
            padding: '20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'section',
        category: 'layout',
        name: 'Section',
        icon: '🗂️',
        description: 'Page section',
        defaultProperties: {},
        defaultStyles: {
            padding: '40px 20px',
            width: '100%',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'grid',
        category: 'layout',
        name: 'Grid',
        icon: '⊞',
        description: 'CSS Grid layout',
        defaultProperties: { columns: 3 },
        defaultStyles: {
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: '20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'flex',
        category: 'layout',
        name: 'Flex',
        icon: '⊟',
        description: 'Flexbox layout',
        defaultProperties: {},
        defaultStyles: {
            display: 'flex',
            gap: '20px',
            alignItems: 'center',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'row',
        category: 'layout',
        name: 'Row',
        icon: '↔️',
        description: 'Horizontal row',
        defaultProperties: {},
        defaultStyles: {
            display: 'flex',
            flexDirection: 'row',
            gap: '20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'column',
        category: 'layout',
        name: 'Column',
        icon: '↕️',
        description: 'Vertical column',
        defaultProperties: {},
        defaultStyles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },

    // ============= NAVIGATION ELEMENTS =============
    {
        type: 'navbar',
        category: 'navigation',
        name: 'Navbar',
        icon: '🧭',
        description: 'Navigation bar',
        defaultProperties: {
            items: [
                { label: 'Home', href: '/' },
                { label: 'About', href: '/about' },
                { label: 'Contact', href: '/contact' },
            ],
        },
        defaultStyles: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '16px 32px',
            backgroundColor: '#ffffff',
            borderBottom: '1px solid #e5e7eb',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'footer',
        category: 'navigation',
        name: 'Footer',
        icon: '👣',
        description: 'Page footer',
        defaultProperties: { text: '© 2025 Company Name. All rights reserved.' },
        defaultStyles: {
            padding: '40px 20px',
            backgroundColor: '#1f2937',
            color: '#ffffff',
            textAlign: 'center',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'sidebar',
        category: 'navigation',
        name: 'Sidebar',
        icon: '📑',
        description: 'Side navigation',
        defaultProperties: {},
        defaultStyles: {
            width: '250px',
            padding: '20px',
            backgroundColor: '#f9fafb',
            borderRight: '1px solid #e5e7eb',
        },
        defaultSize: { width: '250px', height: '100%' },
    },
    {
        type: 'breadcrumb',
        category: 'navigation',
        name: 'Breadcrumb',
        icon: '🍞',
        description: 'Breadcrumb navigation',
        defaultProperties: {
            items: [
                { label: 'Home', href: '/' },
                { label: 'Products', href: '/products' },
                { label: 'Item', href: '/products/item' },
            ],
        },
        defaultStyles: {
            display: 'flex',
            gap: '8px',
            fontSize: '14px',
            color: '#6b7280',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'menu',
        category: 'navigation',
        name: 'Menu',
        icon: '☰',
        description: 'Menu list',
        defaultProperties: {
            items: [
                { label: 'Option 1', href: '#' },
                { label: 'Option 2', href: '#' },
                { label: 'Option 3', href: '#' },
            ],
        },
        defaultStyles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '4px',
        },
        defaultSize: { width: '200px', height: 'auto' },
    },
    {
        type: 'tabs',
        category: 'navigation',
        name: 'Tabs',
        icon: '📑',
        description: 'Tab navigation',
        defaultProperties: {
            tabs: [
                { label: 'Tab 1', active: true },
                { label: 'Tab 2', active: false },
                { label: 'Tab 3', active: false },
            ],
        },
        defaultStyles: {
            display: 'flex',
            gap: '8px',
            borderBottom: '1px solid #e5e7eb',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },

    // ============= FORM ELEMENTS =============
    {
        type: 'input',
        category: 'forms',
        name: 'Input',
        icon: '📝',
        description: 'Text input field',
        defaultProperties: { placeholder: 'Enter text...', name: 'input' },
        defaultStyles: {
            padding: '10px 14px',
            border: '1px solid #d1d5db',
            borderRadius: '6px',
            fontSize: '16px',
            width: '100%',
        },
        defaultSize: { width: '300px', height: '42px' },
    },
    {
        type: 'textarea',
        category: 'forms',
        name: 'Textarea',
        icon: '📃',
        description: 'Multi-line text input',
        defaultProperties: { placeholder: 'Enter text...', name: 'textarea', rows: 4 },
        defaultStyles: {
            padding: '10px 14px',
            border: '1px solid #d1d5db',
            borderRadius: '6px',
            fontSize: '16px',
            width: '100%',
            resize: 'vertical',
        },
        defaultSize: { width: '300px', height: '120px' },
    },
    {
        type: 'select',
        category: 'forms',
        name: 'Select',
        icon: '🔽',
        description: 'Dropdown select',
        defaultProperties: {
            name: 'select',
            options: ['Option 1', 'Option 2', 'Option 3'],
        },
        defaultStyles: {
            padding: '10px 14px',
            border: '1px solid #d1d5db',
            borderRadius: '6px',
            fontSize: '16px',
            width: '100%',
        },
        defaultSize: { width: '300px', height: '42px' },
    },
    {
        type: 'checkbox',
        category: 'forms',
        name: 'Checkbox',
        icon: '☑️',
        description: 'Checkbox input',
        defaultProperties: { label: 'Checkbox', name: 'checkbox' },
        defaultStyles: {
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'radio',
        category: 'forms',
        name: 'Radio',
        icon: '🔘',
        description: 'Radio button',
        defaultProperties: {
            label: 'Radio',
            name: 'radio',
            options: ['Option 1', 'Option 2'],
        },
        defaultStyles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '8px',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'switch',
        category: 'forms',
        name: 'Switch',
        icon: '🔀',
        description: 'Toggle switch',
        defaultProperties: { label: 'Toggle', name: 'switch' },
        defaultStyles: {
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'form',
        category: 'forms',
        name: 'Form',
        icon: '📋',
        description: 'Form container',
        defaultProperties: { action: '#', method: 'POST' },
        defaultStyles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '16px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'label',
        category: 'forms',
        name: 'Label',
        icon: '🏷️',
        description: 'Form label',
        defaultProperties: { text: 'Label', for: '' },
        defaultStyles: {
            fontSize: '14px',
            fontWeight: '500',
            color: '#374151',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },

    // ============= CONTENT ELEMENTS =============
    {
        type: 'card',
        category: 'content',
        name: 'Card',
        icon: '🃏',
        description: 'Content card',
        defaultProperties: { title: 'Card Title', text: 'Card description goes here.' },
        defaultStyles: {
            padding: '24px',
            backgroundColor: '#ffffff',
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        },
        defaultSize: { width: '300px', height: 'auto' },
    },
    {
        type: 'table',
        category: 'content',
        name: 'Table',
        icon: '📊',
        description: 'Data table',
        defaultProperties: {
            headers: ['Column 1', 'Column 2', 'Column 3'],
            rows: [
                ['Data 1', 'Data 2', 'Data 3'],
                ['Data 4', 'Data 5', 'Data 6'],
            ],
        },
        defaultStyles: {
            width: '100%',
            border: '1px solid #e5e7eb',
            borderCollapse: 'collapse',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'list',
        category: 'content',
        name: 'List',
        icon: '📝',
        description: 'Bulleted/numbered list',
        defaultProperties: {
            listItems: ['Item 1', 'Item 2', 'Item 3'],
            ordered: false,
        },
        defaultStyles: {
            padding: '0 0 0 20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'accordion',
        category: 'content',
        name: 'Accordion',
        icon: '🎵',
        description: 'Expandable accordion',
        defaultProperties: {
            sections: [
                { title: 'Section 1', content: 'Content 1' },
                { title: 'Section 2', content: 'Content 2' },
            ],
        },
        defaultStyles: {
            border: '1px solid #e5e7eb',
            borderRadius: '6px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'collapse',
        category: 'content',
        name: 'Collapse',
        icon: '📁',
        description: 'Collapsible section',
        defaultProperties: { title: 'Click to expand', content: 'Hidden content' },
        defaultStyles: {
            border: '1px solid #e5e7eb',
            borderRadius: '6px',
            padding: '12px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'badge',
        category: 'content',
        name: 'Badge',
        icon: '🏅',
        description: 'Small badge',
        defaultProperties: { text: 'Badge', variant: 'primary' },
        defaultStyles: {
            padding: '4px 8px',
            borderRadius: '4px',
            fontSize: '12px',
            fontWeight: '500',
            backgroundColor: '#3b82f6',
            color: '#ffffff',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'tag',
        category: 'content',
        name: 'Tag',
        icon: '🏷️',
        description: 'Tag label',
        defaultProperties: { text: 'Tag' },
        defaultStyles: {
            padding: '6px 12px',
            borderRadius: '16px',
            fontSize: '14px',
            backgroundColor: '#f3f4f6',
            color: '#374151',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },

    // ============= MEDIA ELEMENTS =============
    {
        type: 'image',
        category: 'media',
        name: 'Image',
        icon: '🖼️',
        description: 'Image element',
        defaultProperties: { src: '/api/pexels-image?q=technology', alt: 'Image' },
        defaultStyles: {
            width: '100%',
            height: 'auto',
            borderRadius: '8px',
        },
        defaultSize: { width: '400px', height: '300px' },
    },
    {
        type: 'video',
        category: 'media',
        name: 'Video',
        icon: '🎥',
        description: 'Video player',
        defaultProperties: { src: '', controls: true },
        defaultStyles: {
            width: '100%',
            borderRadius: '8px',
        },
        defaultSize: { width: '600px', height: '400px' },
    },
    {
        type: 'gallery',
        category: 'media',
        name: 'Gallery',
        icon: '🖼️',
        description: 'Image gallery',
        defaultProperties: {
            images: [
                '/api/pexels-image?q=nature',
                '/api/pexels-image?q=city',
                '/api/pexels-image?q=abstract',
            ],
        },
        defaultStyles: {
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: '16px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'carousel',
        category: 'media',
        name: 'Carousel',
        icon: '🎠',
        description: 'Image carousel',
        defaultProperties: {
            images: [
                '/api/pexels-image?q=banner1',
                '/api/pexels-image?q=banner2',
                '/api/pexels-image?q=banner3',
            ],
        },
        defaultStyles: {
            position: 'relative',
            overflow: 'hidden',
            borderRadius: '8px',
        },
        defaultSize: { width: '100%', height: '400px' },
    },
    {
        type: 'avatar',
        category: 'media',
        name: 'Avatar',
        icon: '👤',
        description: 'User avatar',
        defaultProperties: { src: '', alt: 'Avatar', size: 'md' },
        defaultStyles: {
            borderRadius: '50%',
            width: '48px',
            height: '48px',
        },
        defaultSize: { width: '48px', height: '48px' },
    },
    {
        type: 'logo',
        category: 'media',
        name: 'Logo',
        icon: '🎯',
        description: 'Logo image',
        defaultProperties: { src: '', alt: 'Logo' },
        defaultStyles: {
            width: '120px',
            height: 'auto',
        },
        defaultSize: { width: '120px', height: 'auto' },
    },

    // ============= INTERACTIVE ELEMENTS =============
    {
        type: 'modal',
        category: 'interactive',
        name: 'Modal',
        icon: '🪟',
        description: 'Modal dialog',
        defaultProperties: { title: 'Modal Title', content: 'Modal content' },
        defaultStyles: {
            position: 'fixed',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            backgroundColor: '#ffffff',
            padding: '24px',
            borderRadius: '8px',
            boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)',
            zIndex: '1000',
        },
        defaultSize: { width: '500px', height: 'auto' },
    },
    {
        type: 'dropdown',
        category: 'interactive',
        name: 'Dropdown',
        icon: '⏬',
        description: 'Dropdown menu',
        defaultProperties: {
            trigger: 'Click me',
            options: ['Option 1', 'Option 2', 'Option 3'],
        },
        defaultStyles: {
            position: 'relative',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'tooltip',
        category: 'interactive',
        name: 'Tooltip',
        icon: '💬',
        description: 'Hover tooltip',
        defaultProperties: { text: 'Tooltip', content: 'Tooltip content' },
        defaultStyles: {
            position: 'relative',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'alert',
        category: 'interactive',
        name: 'Alert',
        icon: '⚠️',
        description: 'Alert message',
        defaultProperties: {
            text: 'This is an alert message',
        },
        defaultStyles: {
            padding: '12px 16px',
            borderRadius: '6px',
            backgroundColor: '#dbeafe',
            color: '#1e40af',
            border: '1px solid #93c5fd',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'toast',
        category: 'interactive',
        name: 'Toast',
        icon: '🍞',
        description: 'Toast notification',
        defaultProperties: { text: 'Toast message' },
        defaultStyles: {
            position: 'fixed',
            bottom: '20px',
            right: '20px',
            padding: '12px 16px',
            borderRadius: '6px',
            backgroundColor: '#10b981',
            color: '#ffffff',
            boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },
    {
        type: 'popover',
        category: 'interactive',
        name: 'Popover',
        icon: '💭',
        description: 'Popover content',
        defaultProperties: { trigger: 'Click', content: 'Popover content' },
        defaultStyles: {
            position: 'relative',
        },
        defaultSize: { width: 'auto', height: 'auto' },
    },

    // ============= ADVANCED ELEMENTS =============
    {
        type: 'chart',
        category: 'advanced',
        name: 'Chart',
        icon: '📈',
        description: 'Data chart',
        defaultProperties: {
            type: 'bar',
            data: { labels: ['A', 'B', 'C'], values: [10, 20, 30] },
        },
        defaultStyles: {
            width: '100%',
            height: '300px',
        },
        defaultSize: { width: '100%', height: '300px' },
    },
    {
        type: 'progress',
        category: 'advanced',
        name: 'Progress',
        icon: '📊',
        description: 'Progress bar',
        defaultProperties: { value: '50', max: '100' },
        defaultStyles: {
            width: '100%',
            height: '8px',
            backgroundColor: '#e5e7eb',
            borderRadius: '4px',
        },
        defaultSize: { width: '100%', height: '8px' },
    },
    {
        type: 'calendar',
        category: 'advanced',
        name: 'Calendar',
        icon: '📅',
        description: 'Date calendar',
        defaultProperties: {},
        defaultStyles: {
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
            padding: '16px',
        },
        defaultSize: { width: '350px', height: '350px' },
    },
    {
        type: 'map',
        category: 'advanced',
        name: 'Map',
        icon: '🗺️',
        description: 'Interactive map',
        defaultProperties: { center: { lat: 0, lng: 0 }, zoom: 10 },
        defaultStyles: {
            width: '100%',
            height: '400px',
            borderRadius: '8px',
        },
        defaultSize: { width: '100%', height: '400px' },
    },
    {
        type: 'timeline',
        category: 'advanced',
        name: 'Timeline',
        icon: '⏳',
        description: 'Event timeline',
        defaultProperties: {
            events: [
                { title: 'Event 1', date: '2024-01-01' },
                { title: 'Event 2', date: '2024-06-01' },
            ],
        },
        defaultStyles: {
            padding: '20px',
        },
        defaultSize: { width: '100%', height: 'auto' },
    },
    {
        type: 'stats',
        category: 'advanced',
        name: 'Stats',
        icon: '📊',
        description: 'Statistics display',
        defaultProperties: {
            title: 'Total Users',
            value: '1,234',
            change: '+12%',
        },
        defaultStyles: {
            padding: '20px',
            backgroundColor: '#ffffff',
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
        },
        defaultSize: { width: '200px', height: 'auto' },
    },
];

// Helper function to get template by type
export function getElementTemplate(type: string): ElementTemplate | undefined {
    return ELEMENT_TEMPLATES.find(t => t.type === type);
}

// Get templates by category
export function getElementsByCategory(category: string): ElementTemplate[] {
    return ELEMENT_TEMPLATES.filter(t => t.category === category);
}
