"use client";

import React from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { motion } from "motion/react";
import {
  Shield,
  Lock,
  Code,
  AlertTriangle,
  EyeOff,
  Fingerprint,
} from "lucide-react";

export default function SecurityPage() {
  return (
    <main className="min-h-screen bg-background">
      {/* HEADER */}
      <div className="max-w-7xl mx-auto px-6 py-10">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <Link
              href="/"
              className="text-sm text-muted-foreground hover:underline"
            >
              ← Back to Home
            </Link>

            <h1 className="text-4xl md:text-5xl font-bold">
              Secure & Stable by Design
            </h1>

            <p className="text-muted-foreground max-w-2xl text-sm">
              AvatarFlowX generates backend logic using hardened templates,
              typed contracts, structured validation layers, and security-first
              patterns inspired by industry-standard services.
            </p>
          </div>

          <div className="hidden md:flex items-center gap-3">
            <Badge>Enterprise-Grade</Badge>
            <Button asChild>
              <Link href="/editor">Open Editor</Link>
            </Button>
          </div>
        </div>
      </div>

      {/* TOP SECTION — Quick Facts */}
      <section className="max-w-7xl mx-auto px-6 pb-16">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
          {/* LEFT SIDE */}
          <div className="lg:col-span-7 space-y-5">
            {/* NEW Security Overview Panel (fills the empty white space cleanly) */}
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35 }}
              className="rounded-2xl border bg-card p-6 shadow-sm mt-6 max-w-md"
            >
              <h3 className="text-lg font-semibold mb-2 flex items-center gap-2">
                <Shield className="size-5" />
                Security Overview
              </h3>

              <p className="text-sm text-muted-foreground mb-4 leading-relaxed">
                AvatarFlowX generates backend logic using security-hardened
                templates, predictable API contracts, typed validation, and
                sandboxed execution.
              </p>

              <ul className="space-y-3 text-sm">
                <li className="flex items-start gap-2">
                  <Lock className="size-4 mt-1 text-accent-foreground" />
                  <span>Runtime-safe Zod validation for every endpoint.</span>
                </li>
                <li className="flex items-start gap-2">
                  <EyeOff className="size-4 mt-1 text-accent-foreground" />
                  <span>
                    Sanitized input to block XSS and injection attempts.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <Fingerprint className="size-4 mt-1 text-accent-foreground" />
                  <span>
                    Authentication hooks ready for JWT or OAuth providers.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <AlertTriangle className="size-4 mt-1 text-accent-foreground" />
                  <span>
                    Guard rails prevent invalid flows or dangerous operations.
                  </span>
                </li>
              </ul>
            </motion.div>

            <Button asChild size="lg">
              <Link href="/docs/security">View Technical Docs</Link>
            </Button>
          </div>

          {/* RIGHT SIDE — enhanced Quick Facts carousel */}
          <motion.div
            whileHover={{ scale: 1.02 }}
            className="lg:col-span-5 rounded-2xl border bg-card shadow-lg p-6 space-y-6"
          >
            <div className="flex items-center gap-3">
              <Shield className="size-5" />
              <h3 className="text-lg font-semibold">Quick Facts</h3>
            </div>

            {/* FACTS LIST */}
            <div className="space-y-4 text-sm text-muted-foreground">
              <FactItem
                icon={<Lock className="size-4" />}
                title="Strict Input Validation"
                desc="Every endpoint uses autogenerated Zod schemas to validate input before reaching business logic."
              />
              <FactItem
                icon={<EyeOff className="size-4" />}
                title="Sanitization Layer"
                desc="User input is sanitized to protect against common attack surfaces (XSS, injection, malformed payloads)."
              />
              <FactItem
                icon={<Code className="size-4" />}
                title="Safe API Scaffolding"
                desc="Generated endpoints follow consistent patterns: typed handlers, predictable errors, stable responses."
              />
              <FactItem
                icon={<AlertTriangle className="size-4" />}
                title="Runtime Guard Rails"
                desc="Built-in checks prevent unsafe operations, invalid state transitions, or untrusted execution flows."
              />
              <FactItem
                icon={<Fingerprint className="size-4" />}
                title="Auth-Ready Blueprint"
                desc="Generated apps include clean hooks for JWT/session validation — plug into any provider instantly."
              />
            </div>
          </motion.div>
        </div>
      </section>

      {/* DEEP DIVE SECTIONS */}
      <section className="max-w-7xl mx-auto px-6 pb-24 space-y-16">
        {/* SECTION 1 */}
        <DeepDiveBlock
          title="1. Input Validation & Contract Enforcement"
          icon={<Lock className="size-5" />}
          description="All generated endpoints enforce runtime-safe Zod schemas with strong TypeScript support."
          code={`export const SubmitSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
});

export async function POST(req) {
  const body = await req.json();
  const parsed = SubmitSchema.parse(body); // throws on invalid input
  return NextResponse.json({ ok: true });
}`}
        />

        {/* SECTION 2 */}
        <DeepDiveBlock
          title="2. Sanitization & Safe Default Behaviors"
          icon={<EyeOff className="size-5" />}
          description="AvatarFlowX sanitizes dangerous patterns and escapes untrusted content before storage or rendering."
          code={`import DOMPurify from "isomorphic-dompurify";

const safeHTML = DOMPurify.sanitize(userInput);`}
        />

        {/* SECTION 3 */}
        <DeepDiveBlock
          title="3. Stable API & Error Contracts"
          icon={<Code className="size-5" />}
          description="Generated handlers use predictable error envelopes, ensuring consistent response shapes across routes."
          code={`return NextResponse.json({
  ok: false,
  error: "Invalid payload",
  details: err.message,
});`}
        />

        {/* SECTION 4 */}
        <DeepDiveBlock
          title="4. Guard Rails & Isolation"
          icon={<AlertTriangle className="size-5" />}
          description="Execution layers prevent unsafe access, ensure handler isolation, and avoid untrusted execution paths."
          code={`if (!allowedOperations.includes(operation)) {
  throw new Error("Operation not permitted");
}`}
        />
      </section>
    </main>
  );
}

/* ———————————————————————— */
/* COMPONENTS */
/* ———————————————————————— */

function FactItem({
  icon,
  title,
  desc,
}: {
  icon: React.ReactNode;
  title: string;
  desc: string;
}) {
  return (
    <div className="flex items-start gap-3">
      <span className="mt-1 text-accent-foreground">{icon}</span>
      <div>
        <div className="font-medium text-foreground">{title}</div>
        <div className="text-xs text-muted-foreground">{desc}</div>
      </div>
    </div>
  );
}

function DeepDiveBlock({
  icon,
  title,
  description,
  code,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
  code: string;
}) {
  return (
    <motion.div
      whileHover={{ y: -4 }}
      className="rounded-xl border p-6 bg-card shadow-sm"
    >
      <div className="flex items-center gap-3 mb-3">
        {icon}
        <h3 className="text-lg font-semibold">{title}</h3>
      </div>

      <p className="text-sm text-muted-foreground mb-4">{description}</p>

      <div className="rounded-lg bg-black text-white p-4 text-xs font-mono overflow-auto border border-zinc-700">
        <pre>{code}</pre>
      </div>
    </motion.div>
  );
}
